/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_leonding_htl_features_analyze_BPMAnalyzer */

#ifndef _Included_at_leonding_htl_features_analyze_BPMAnalyzer
#define _Included_at_leonding_htl_features_analyze_BPMAnalyzer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_leonding_htl_features_analyze_BPMAnalyzer
 * Method:    analyzeBPM
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_at_leonding_htl_features_analyze_BPMAnalyzer_analyzeBPM
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
