services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin
    healthcheck:
      test: pg_isready --dbname=admin --username=admin
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - my-network

volumes:
  postgres:

networks:
  my-network:
    external: true