services:
  postgres:
#    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin
    healthcheck:
      test: pg_isready --dbname=admin --username=admin
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 2s

  backend:
#    container_name: backend
    image: backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/admin
      - quarkus.datasource.username=admin
      - quarkus.datasource.password=admin
    healthcheck:
        test: curl -f http://localhost:8080/api/q/health
        start_period: 30s
        start_interval: 2s
        retries: 10

  nginx:
    image: frontend
    ports:
      - "4200:80"
    healthcheck:
      test: curl --fail --head -fsS http://localhost || exit 1
      interval: 40s
      timeout: 30s
      retries: 2
      start_period: 10s
    depends_on:
      backend:
        condition: service_healthy
volumes:
  postgres:
