services:
  ml:
    image: ml
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ./song-storage:/app/song-storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ml:5000/health"]
      start_period: 30s
      interval: 2s
      retries: 10
    networks:
      - my-network

networks:
  my-network:
    external: true