services:
  ml:
    image: ml
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5001:5001"
    volumes:
      - ./song-storage:/app/song-storage
    healthcheck:
      test: curl -f http://ml:5001/health
      start_period: 30s
      interval: 2s
      retries: 10