services:
  backend:
    image: backend:latest
    depends_on:
      postgres:
        condition: service_healthy
      ml:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./song-storage:/app/song-storage
    environment:
      - SONG_STORAGE_DIRECTORY=/app/song-storage
      - SONG_STORAGE_PATH=/app/song-storage
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/postgres
      - QUARKUS_DATASOURCE_USERNAME=danceable
      - QUARKUS_DATASOURCE_PASSWORD=danceable
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=none
      - QUARKUS_REST_CLIENT_ML_SERVICE_URL=http://ml:5001/
    healthcheck:
      test: curl -f http://backend:8080/q/health/live
      start_period: 30s
      interval: 60s
      retries: 10