services:
  backend:
    image: backend
    depends_on:
      postgres:
        condition: service_healthy
#      ml:
#        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./song-storage:/app/song-storage
    healthcheck:
      test: curl -f http://backend:8080/q/health/live
      start_period: 30s
      interval: 60s
      retries: 10