#services:
#  backend:
#    image: ghcr.io/2425-4bhitm-itp/backend:latest
#    depends_on:
#      postgres:
#        condition: service_healthy
##      ml:
##        condition: service_healthy
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./song-storage:/app/song-storage
#    healthcheck:
#      test: curl -f http://backend:8080/q/health/live
#      start_period: 30s
#      interval: 60s
#      retries: 10


services:
  backend:
    image: ghcr.io/2425-4bhitm-itp/backend:latest
    depends_on:
      postgres:
        condition: service_healthy
      ml:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./song-storage:/app/song-storage
    environment:
      - SONG_STORAGE_DIRECTORY=/app/song-storage
      - SONG_STORAGE_PATH=/app/song-storage
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/admin
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=admin
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create
    healthcheck:
      test: curl -f http://backend:8080/q/health/live
      start_period: 30s
      interval: 60s
      retries: 10