services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=danceable
      - POSTGRES_USER=danceable
      - POSTGRES_DB=danceable
    healthcheck:
      test: pg_isready --dbname=danceable --username=danceable
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres: