services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=demo
      - POSTGRES_DB=demo
    healthcheck:
      test: pg_isready --dbname=demo --username=demo
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres: