services:
  ml:
    image: ml:latest
    ports:
      - "5002:5002"
    volumes:
      - ./song-storage:/app/song-storage
    healthcheck:
      test: curl -f http://ml:5001/health
      start_period: 30s
      interval: 60s
      retries: 10
