###
GET https://it210190.cloud.htl-leonding.ac.at/dances

### Upload WEBM audio stream for classification
POST http://localhost:8080/audio/uploadWebmStream/tmp
Content-Type: audio/webm

< ./sample.webm

