### backend is up and running.

http://localhost:8080/q/health/live

### backend is ready to serve requests

http://localhost:8080/q/health/ready

### backend is started

http://localhost:8080/q/health/started

### accumulating all health check procedures in backend

http://localhost:8080/q/health