### test backend db connection (and get dances)

GET http://localhost:8080/dances

###

GET http://localhost:8080/songs

###

POST http://localhost:8080/songs
Content-Type: Application/JSON

{
    "title": "tmpded song"
}

###

GET http://localhost:8080/clips

###

POST http://localhost:8080/clips
Content-Type: Application/JSON

{
  "song": {
    "id": 1
  },
  "dances": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ],
  "songSnippetIndex": 13,
  "speed": 12,
  "fileName": "snippet12.mp3"
}


### test backend and ml service

POST http://localhost:8080/upload/file
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="44bpm_jive_bad-moon-rising-creedence-clerwater-revival-1.wav"
Content-Type: audio/wav

< (your_path) /testlieder/0-100/44bpm_jive_bad-moon-rising-creedence-clerwater-revival-1.wav
--boundary
Content-Disposition: form-data; name="fileName"

44bpm_jive_bad-moon-rising-creedence-clerwater-revival-1.wav