### split all files in /app/song-storage/songs

POST https://it210190.cloud.htl-leonding.ac.at/split_files

### split all files in /app/song-storage/songs and sort them into their respective class

POST https://it210190.cloud.htl-leonding.ac.at/split_and_sort
content-type: application/json

{
  "segment_length": 3000
}

### eextract features from all files

POST https://it210190.cloud.htl-leonding.ac.at/process_all_audio
content-type: application/json

{
  "delete_files": true,
  "worker_count": 16
}

### start training

POST https://it210190.cloud.htl-leonding.ac.at/train
Content-Type: application/json

{
    "disabled_labels": [
      "foxtrott"
    ],
    "test_size": 0.2,
    "batch_size": 64,
    "epochs": 100,
    "downsampling": false
}

### evaluate the newest model

GET https://it210190.cloud.htl-leonding.ac.at/evaluate

### classify local file

POST https://it210190.cloud.htl-leonding.ac.at/classify_audio?file_path=/opt/application/data/Sway_Michael_Buble_Handy.wav

### check if pods are processing

GET https://it210190.cloud.htl-leonding.ac.at/processing

### test hyperparameters

POST https://it210190.cloud.htl-leonding.ac.at/hyperparameter-test
Content-Type: application/json

{
  "search_space": {
    "train": {
      "batch_size": [64, 128, 256, 512],
      "epochs": [100],
      "test_size": [0.2],
      "downsampling": [false],
      "disabled_labels": ["foxtrott"]
    },
    "model": {
      "filters": [[32, 64, 128], [64, 128, 256]],
      "dense_units": [64, 128, 256, 512],
      "dropout_rate": [0.2, 0.3, 0.5],
      "learning_rate": [0.0003, 0.0001],
      "kernel_size": [[3, 3], [5, 5], [7, 7]]
    }
  },
  "replicas": 8
}

### test backend

POST https://it210190.cloud.htl-leonding.ac.at/audio/uploadStream
Content-Type: audio/wave

< ../data/Sway_Michael_Buble.wav
