### shorten

POST https://it210190.cloud.htl-leonding.ac.at/split_files

### aufbereiten

POST https://it210190.cloud.htl-leonding.ac.at/split_and_sort
content-type: application/json

{
  "segment_length": 3000
}

### process all audio

POST https://it210190.cloud.htl-leonding.ac.at/process_all_audio
content-type: application/json

{
  "delete_files": true,
  "worker_count": 16
}

### train

POST https://it210190.cloud.htl-leonding.ac.at/train
Content-Type: application/json

{
    "disabled_labels": [
        "foxtrott"
    ],
    "test_size": 0.2,
    "batch_size": 64,
    "epochs": 100,
    "downsampling": false
}

### evaluate

GET https://it210190.cloud.htl-leonding.ac.at/evaluate

### classify

POST https://it210190.cloud.htl-leonding.ac.at/classify_audio?file_path=/opt/application/data/Sway_Michael_Buble_Handy.wav

### is proccessing

GET https://it210190.cloud.htl-leonding.ac.at/processing

### test hyperparameters

POST https://it210190.cloud.htl-leonding.ac.at/hyperparameter-test
Content-Type: application/json

{
  "search_space": {
    "train": {
      "batch_size": [64, 128, 256, 512],
      "epochs": [100],
      "test_size": [0.2],
      "downsampling": [false],
      "disabled_labels": ["foxtrott"]
    },
    "model": {
      "filters": [[32, 64, 128], [32, 64], [64, 128, 256]],
      "dense_units": [64, 128, 256, 512],
      "dropout_rate": [0.2, 0.3, 0.5],
      "learning_rate": [0.01, 0.001, 0.0003, 0.0001],
      "kernel_size": [[3, 3], [5, 5], [7, 7]]
    }
  },
  "replicas": 30
}
