### shorten

POST https://it210190.cloud.htl-leonding.ac.at/split_files

### aufbereiten

POST https://it210190.cloud.htl-leonding.ac.at/split_and_sort
content-type: application/json

{
  "segment_length": 3000
}

### process all audio

POST https://it210190.cloud.htl-leonding.ac.at/process_all_audio
content-type: application/json

{
  "delete_files": true,
  "worker_count": 16
}

### train

POST https://it210190.cloud.htl-leonding.ac.at/train
Content-Type: application/json

{
    "disabled_labels": [
        "foxtrott",
        "tango"
    ],
    "test_size": 0.2,
    "batch_size": 128,
    "epochs": 100,
    "downsampling": false
}

### evaluate

GET https://it210190.cloud.htl-leonding.ac.at/evaluate

### classify

POST https://it210190.cloud.htl-leonding.ac.at/classify_audio?file_path=/opt/application/data/Sway_Michael_Buble_Handy.wav

### is proccessing

GET https://it210190.cloud.htl-leonding.ac.at/processing
