@startuml
title Danceable Microservice Architecture

package "Web Frontend" {
  [Website]
  note bottom of [Website]
    - Admin Board
    - Recorder and Dances
  end note
}

package "Backend" {
  [Server]
  note bottom of [Server]
    - /admin: Train AI based on Fourier analysis
    - /user: Recognition based on Fourier analysis
  end note
}

package "Database" {
  [DB]
  note bottom of [DB]
    Stores information about songs
  end note
}

package "Volume" {
  [Song Storage]
  note bottom of [Song Storage]
    Stores songs for training
  end note
}

package "Machine Learning" {
  [AI]
  note bottom of [AI]
    - Train with Fourier data
    - Recognize dance styles
  end note
}

[Website] --> [Server] : REST
[Server] -up-> [DB] : REST
[Server] --> [AI] : REST
[Server] --> [Song Storage]
[AI] -left-> [Song Storage]
@enduml