@startuml
title Danceable Microservice Architecture

package "Frontend" {
  [Website]
  note bottom of [Website]
      - Technology: Webpack (TypeScript)
         served by Nginx
      - Features:
        - Admin Board
        - User Interface
    end note
}

package "Backend" {
  [Server]
  note bottom of [Server]
      - Technology: Quarkus (Java)
      - Features:
        - manage song snippets
        - command ML
        - recognize songs using ML
    end note
}

package "Database" {
  [DB]
  note bottom of [DB]
      - Technology: PostgreSQL
      - Feature: store song snippets metadata
         and corresponding dance styles
    end note
}

package "Volume" {
  [Song Storage]
  note bottom of [Song Storage]
      - Technology: mapped docker volume
      - Feature: store song snippets for training
    end note
}

package "Machine Learning" {
  [ML]
  note bottom of [ML]
      - Technology: Keras (Python)
      - Features:
        - train
        - recognize dance styles
    end note
}

package "Spectrogram Generation" {
  [Spectrogram]
  note bottom of [Spectrogram]
      - Generate spectrogram
    end note
}

[Website] --> [Server] : REST
[Server] -up-> [DB] : REST
[Server] --> [ML] : REST
[Server] --> [Song Storage]
[ML] -right-> [Song Storage]
[ML] --> [Server]

[Server] -up-> [Spectrogram] : REST
[Spectrogram] --> [Volume]
[Spectrogram] --> [Server]
@enduml