@startwbs
<style>
    .levelOne{
        BackgroundColor b13aff
    }

    .levelTwo {
        BackgroundColor dca6ff
    }

</style>

* <b><size:23>Danceable (2080h)</size> <<levelOne>>
** <b><size:15>Projektmanagement (400h)</size><<levelTwo>>
*** Planung und Meilensteine (100h)
**** Anforderungsanalyse
**** MVP-Definition (Minimal Viable Product)
*** SCRUM (200h)
**** Daily SCRUM
**** Sprint Planning
**** Sprint Retrospect
*** Dokumentation (100h)
**** Code-Dokumentation
**** Nutzeranleitung

** <b><size:15>Implementierung (1680h)</size><<levelTwo>>

*** <size:15><b>Frontend - (Web/IOS/Android) (600h) </size><<levelTwo>>
**** UI/UX Design
***** Mockups und Wireframes
***** Interaktionsdesign
***** Mobile Design
**** Implementierung
***** Musik-Upload Seite
***** Musik Recorder
***** Ergebnisseite (Anzeige der tanzbaren Tänze)
***** Fourier-Analyse-Visualisierung
**** Frontend/Backend-Integration
***** API-Anbindung

***< <b><size:15>Backend - Quarkus (800h) </size><<levelTwo>>
**** API Entwicklung
***** Tanz-Erkennung API
**** Analyse
***** Fourier Transformation (Mathe)
***** Datenaufbereitung (fürs Training)
***** Training
***** Visualisierung der Ergebnisse
**** Tests
***** Unit-Tests (Code)
***** Unit-Tests (API)

***< <size:15><b>Datenbank - Postgres (50h)</size><<levelTwo>>
**** Datenbankstruktur
***** Tanz (mit zB Geschwindigkeit, Takt, ...)
***** Benutzerprofile
**** Indexing und Performance

***> <size:15><b>DevOps und Deployment</size><<levelTwo>>
**** Infrastruktur
***** Docker Containerisierung
***** Kubernetes Deployment (optional)
**** Monitoring


@endwbs
