name: Danceable CI/CD Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
#on: [ push ]
#jobs:
#  Explore-GitHub-Actions:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#          cache: 'maven'
#          cache-dependency-path: 'code/backend/pom.xml'
#      - name: Build with Maven
#        working-directory: code/backend
#        run: mvn -B package --file pom.xml
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debug-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List directory structure
        run: |
          echo "Repository structure:"
          ls -la
          echo "Searching for relevant directories:"
          find . -type d -not -path "*/\.*" | sort

  build-and-test-backend:
    needs: debug-structure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Start PostgreSQL
        run: |
          docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:14
          sleep 10

      - name: Find and build backend
        run: |
          # Versuche, das Backend-Verzeichnis zu finden
          if [ -d "backend" ]; then
            cd backend
          elif [ -d "code/backend" ]; then
            cd code/backend
          else
            echo "Backend-Verzeichnis nicht gefunden. Aktuelle Struktur:"
            find . -name "pom.xml" -not -path "*/target/*"
            exit 1
          fi
          
          # Baue das Backend
          if [ -f "./mvnw" ]; then
            chmod +x ./mvnw
            ./mvnw clean package
          else
            mvn clean package
          fi